### Lab 02 - numpy

Name: Dempsey Wade

Class: CSCI 349 - Intro to Data Mining

Semester: 2019SP

Instructor: Brian King

### 1 Create an 52500 x 75 matrix of zeros, stored as X. Then print out the shape of the matrix, the base data type, the total size of the array in bytes (as an integer), and the total size in megabytes with 3 places of significance.

In [1]:
import numpy as np
x = np.zeros((52500,75))
print(x.shape)
print(x.dtype)
print(x.size)
print((x.size * x.itemsize))

(52500, 75)
float64
3937500
31500000


### 2 Resize X to have the same number of elements, but with 100 rows. Show the shape. Show the number of bytes (it should be the same as the previous answer)

In [2]:
np.resize(x, (100, 39375))
print(x.shape)
print(x.dtype)
print(x.size)
print((x.size * x.itemsize))

(52500, 75)
float64
3937500
31500000


### 3 Redo #1, but use a base datatype of 16-bit integers.

In [3]:
x = np.zeros((52500, 75), dtype = np.int16)
print(x.shape)
print(x.dtype)
print(x.size)
print((x.size * x.itemsize))

(52500, 75)
int16
3937500
7875000


### 4 How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.

In [4]:
print(x.ndim)

2


### 5 Enter the following list in your cell:

In [5]:
str_nums = ['2.14', '-9.3', '42']
x = np.asarray(str_nums)
x.astype(float)
print(x)

days = ["Mon","Tue","Wed","Thu","Fri"] 
scores_1 = [9.5, 8.75, 8, 10, 7.75] 
scores_2 = [9, 8, 10, 8.75, 7.25]

['2.14' '-9.3' '42']


### 6 Create a numpy array called scores, that has scores_1 as the first row and scores_2 as the second row, using np.concatenate. Then, change days into a np.array from the list days. Verify the shape of scores and days.

In [6]:
scores = np.asarray
scores = np.concatenate((scores_1, scores_2))
print(scores)
print(scores.shape)
days = np.array((days))
print(days)
print(days.shape)

[ 9.5   8.75  8.   10.    7.75  9.    8.   10.    8.75  7.25]
(10,)
['Mon' 'Tue' 'Wed' 'Thu' 'Fri']
(5,)


### 7 Repeat the previous problem, but repeat it with np.vstack. The array should be identical.

In [7]:
scores = np.vstack((scores_1,scores_2))
print(scores)

[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]


### 8 Compare the result of the expression days == "Fri" if the variable days was a Python list, vs. days being a numpy array. What is the difference? Ingeneral, how does numpy deal with standard comparison operators?

Numpy gives you the elements in the array that are equal to "Fri". In normal python, you would just get a 'False' output. 

In [8]:
print(days == "Fri")

[False False False False  True]


### 9 Select the scores that fell on Monday

In [9]:
print(scores[..., days == "Mon"])

[[9.5]
 [9. ]]


### 10 Select all of the scores that are NOT on Monday (Hint–look up the ~ operator)

In [10]:
print(scores[..., days != "Mon"])

[[ 8.75  8.   10.    7.75]
 [ 8.   10.    8.75  7.25]]


### 11  Select the scores that were on Tuesday or Thursday

In [11]:
print(scores[..., (days == "Tue") | (days == "Thu")])

[[ 8.75 10.  ]
 [ 8.    8.75]]


### 12 Show the minimum and maximum scores for the entire array of scores

In [12]:
print(np.amin(scores))
print(np.amax(scores))

7.25
10.0


### 13  Show the minimum scores for each week as a new array with the same dimensions (hint – use the keepdims parameter). Your result should be something like:

In [13]:
print(np.amin(scores, axis = 0, keepdims=True))

[[9.   8.   8.   8.75 7.25]]


### 14 Report the day that the maximum score occurred each week.(HINT: use argmax and use that result to index days.)

In [14]:
print(days[np.argmax(scores[0])])
print(days[np.argmax(scores[1])])

Thu
Wed


### 15 Report the mean of the scores of each week

In [15]:
print(np.mean(scores[0]))
print(np.mean(scores[1]))

8.8
8.6


### 16 Suppose the lowest score was dropped from each week. Report the mean of each week, but without the minimum score for that week.

In [16]:
means = scores.mean(axis = 1)
print((means*days.size - scores.min(1))/(days.size-1))

[9.0625 8.9375]


### 17 Convert the scores to fall on a scale from 0-100 instead of 0-10.

In [17]:
scores = scores*10
print(scores)

[[ 95.   87.5  80.  100.   77.5]
 [ 90.   80.  100.   87.5  72.5]]


In [18]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
print(X)

[[48 84 39 54 77]
 [25 16 50 24 27]
 [31 44 31 27 59]
 [93 70 81 74 48]
 [51 77 38 35 39]
 [68 12  1 76 81]
 [ 4  3 20 13 66]
 [76 82 15 72 61]
 [47 29 82 88 14]
 [97 13 70 96 32]]


### 18 Select the first row of X

In [19]:
print(X[0])

[48 84 39 54 77]


### 19 Select the last column of X

In [20]:
print(X[:,-1])

[77 27 59 48 39 81 66 61 14 32]


### 20 Select the first AND last column of X

In [21]:
print(X[:,[0,-1]])

[[48 77]
 [25 27]
 [31 59]
 [93 48]
 [51 39]
 [68 81]
 [ 4 66]
 [76 61]
 [47 14]
 [97 32]]


### 21 Select every other row of X

In [22]:
print(X[::2])

[[48 84 39 54 77]
 [31 44 31 27 59]
 [51 77 38 35 39]
 [ 4  3 20 13 66]
 [47 29 82 88 14]]


### 22 Show the transpose of X, but don't change X itself

In [23]:
print(np.transpose(X))

[[48 25 31 93 51 68  4 76 47 97]
 [84 16 44 70 77 12  3 82 29 13]
 [39 50 31 81 38  1 20 15 82 70]
 [54 24 27 74 35 76 13 72 88 96]
 [77 27 59 48 39 81 66 61 14 32]]


### 23 Select the first column of X and set the result to Y.

In [24]:
Y = np.array
Y = np.copy(X[:,0])
print(Y)

[48 25 31 93 51 68  4 76 47 97]


### 24 Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change?

Yes both values changed in my first solution. I have since fixed it. 

In [25]:
Y[0] += 1
print(Y)
print(X[:,0])

[49 25 31 93 51 68  4 76 47 97]
[48 25 31 93 51 68  4 76 47 97]


### 25 Repeat exercise 23, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y and ensure that the corresponding value of X did not change.


As seen above, my value for X did not change while by first value of Y increased by 1. I did it correctly above.

### 26 Create an array that contains the sequence of numbers 0, 0.1 ,0.2 , ... 9.8 , 9.9 using arange, as a 10x10 matrix, stored as X.

In [26]:
X = np.arange(0.0, 10.0, .1).reshape(10, 10)

print(X)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]]


### 27 Set the RNG seed to 1234. Then create an array X of uniformly distributed data, with all values between 1.0 and 10.0. Then, show the mean, the median, the minimum and maximum values of X.

In [27]:
np.random.seed(1234)
X = np.random.uniform(1.0, 10.0, 100) 
# Don't know large to make it, so i made it have 100 elements so I 
# could still print it 
print(X)

print("Mean: ", np.mean(X))
print("Median: ", np.median(X))
print("Min: ", np.amin(X))
print("Max: ", np.amax(X))


[2.72367505 6.59897894 4.93954965 8.06822725 8.01978227 3.45333345
 3.4881783  8.2168496  9.62325418 8.88339371 4.22035543 5.50895613
 7.15116642 7.41431824 4.33225679 6.05076567 5.52774849 1.12391605
 7.95543959 8.94377072 4.28397386 6.53856561 1.67843117 4.31941605
 9.39826092 6.86240329 4.5748232  8.09857129 3.8515251  6.11288787
 8.82214651 4.92556082 8.21932878 2.29390142 7.33834874 7.34123177
 2.96912895 9.32380866 4.9792668  9.18384363 1.53828301 2.65858375
 1.42619751 7.07392849 6.35162302 5.79979147 1.38991656 6.05289772
 3.96701601 5.5267015  2.00704886 6.46474336 6.09350179 1.06087656
 6.55697538 9.20910598 8.1147172  9.9287332  9.62921586 8.12767722
 3.56725864 6.62425035 5.30284416 2.76107661 4.44085707 1.48486317
 5.06483567 9.83804267 2.1154843  2.07442808 7.64670751 6.2857327
 5.24469281 1.96414135 3.06296709 9.09968675 4.75078184 5.82266496
 1.05587665 3.70577535 4.93203855 6.50934097 9.26378268 6.63163003
 7.35397809 2.34850344 7.71457068 8.47906293 6.70353192 4.94478

### 28 [M] Define what is meant by a normal distribution. What are the parameters of a normal distribution?

Normal distribution is when data is represented as a "bell curve" that can show probabilities and outliers. 
The parameters are the mean and standard deviation. 

### 29 [M] In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?

Simply, if you run an experiment a large number of times, your experimental outcome should be very close to the true outcome. 

### 30 Write a function called test_normal_dist. The purpose of this function is to evaluate the law of large numbers. It should have four parameters:

In [28]:
def test_normal_dist(mu, sd, vec_length, num_trials):
    sums = 0
    np.random.seed(1234)
    for i in range(num_trials):
        s = np.random.normal(mu, sd, vec_length)
        mean = s.mean()
        deviation = abs(mean-mu)
        sums += deviation
    return (sums/num_trials)
    


### 31 Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two dimensions. the first being the vector length, and the second being the average deviation resulting from your test_normal_dist function.

In [29]:

vec_lengths = [10, 100, 1000, 10000, 100000]
out = []
for n in vec_lengths:
    d = test_normal_dist(8, 30, n, 100)
    out.append([n, d])
out

[[10, 7.158612553329618],
 [100, 2.428875978896355],
 [1000, 0.6687000204893795],
 [10000, 0.23832582733933094],
 [100000, 0.0733051829579181]]